services:
  app:
    build: .
    container_name: radiusapi-app-1
    network_mode: host
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=radius
      - DB_PASS=ArrowNet@DB123!@#
      - DB_PORT=3306
      - DB_NAME=radius
      - MASTER_USER=radius
      - MASTER_PASS=Kisan@radius
      - JWT_SECRET=freeradius@123Secret
      - JWT_TTL=1h
      - PORT=3005
      - NAS_COA_PORT=3799
      - RADCLIENT_TIMEOUT_MS=15000
    restart: unless-stopped