version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=172.17.0.1
      - DB_USER=radius
      - DB_PASS=ArrowNet@DB123!@#
      - DB_PORT=3306
      - DB_NAME=radius
      - MASTER_USER=radius
      - MASTER_PASS=Kisan@radius
      - JWT_SECRET=freeradius@123Secret
      - JWT_TTL=1h
      - PORT=3005
      - NAS_COA_PORT=3799
